[package]
name = "LinuxSoftwareSnapshoter"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "snapshoter"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.39", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
